CREATE TABLE "usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "email" varchar UNIQUE,
  "senha" varchar
);

CREATE TABLE "tarefas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar,
  "descricao" text,
  "status" varchar,
  "data_criacao" date,
  "data_conclusao" date,
  "usuario_id" int
);

CREATE TABLE "categorias" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar
);

CREATE TABLE "tarefas_categorias" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tarefa_id" int,
  "categoria_id" int
);

ALTER TABLE "tarefas" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "tarefas_categorias" ADD FOREIGN KEY ("tarefa_id") REFERENCES "tarefas" ("id");

ALTER TABLE "tarefas_categorias" ADD FOREIGN KEY ("categoria_id") REFERENCES "categorias" ("id");

CREATE TABLE "historico_tarefas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tarefa_id" int,
  "data_modificacao" date,
  "status_anterior" varchar,
  "status_atual" varchar
);

-- Inserir alguns usuários de teste
INSERT INTO usuarios (nome, email, senha) VALUES 
('João Silva', 'joao@email.com', '123456'),
('Maria Santos', 'maria@email.com', '123456'),
('Pedro Oliveira', 'pedro@email.com', '123456');

-- Inserir algumas categorias de teste
INSERT INTO categorias (nome) VALUES 
('Trabalho'),
('Pessoal'),
('Estudos'),
('Casa');

-- Inserir algumas tarefas de teste
INSERT INTO tarefas (titulo, descricao, status, data_criacao, usuario_id) VALUES 
('Finalizar relatório mensal', 'Compilar dados de vendas e criar apresentação', 'pendente', CURRENT_DATE, 1),
('Comprar ingredientes para jantar', 'Lista: arroz, feijão, carne, salada', 'pendente', CURRENT_DATE, 2),
('Estudar para prova de JavaScript', 'Revisar conceitos de async/await e promises', 'em-andamento', CURRENT_DATE, 3),
('Organizar armário do quarto', 'Separar roupas que não uso mais', 'concluida', CURRENT_DATE - INTERVAL '2 days', 2);