CREATE TABLE "usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "email" varchar UNIQUE,
  "senha" varchar
);

CREATE TABLE "tarefas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar,
  "descricao" text,
  "status" varchar,
  "data_criacao" date,
  "data_conclusao" date,
  "usuario_id" int
);

CREATE TABLE "categorias" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar
);

CREATE TABLE "tarefas_categorias" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tarefa_id" int,
  "categoria_id" int
);

ALTER TABLE "tarefas" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "tarefas_categorias" ADD FOREIGN KEY ("tarefa_id") REFERENCES "tarefas" ("id");

ALTER TABLE "tarefas_categorias" ADD FOREIGN KEY ("categoria_id") REFERENCES "categorias" ("id");

CREATE TABLE "historico_tarefas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tarefa_id" int,
  "data_modificacao" date,
  "status_anterior" varchar,
  "status_atual" varchar
);